//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvansApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AMS360_Customer
    {
        public int CustNo { get; set; }
        public System.Guid CustId { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string MidName { get; set; }
        public string Addr1 { get; set; }
        public string Addr2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string County { get; set; }
        public string ZipCode { get; set; }
        public string ResAreaCode { get; set; }
        public string ResPhone { get; set; }
        public string ResExt { get; set; }
        public string BusAreaCode { get; set; }
        public string BusPhone { get; set; }
        public string BusExt { get; set; }
        public string FaxAreaCode { get; set; }
        public string FaxPhone { get; set; }
        public string FaxExt { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string KnownSince { get; set; }
        public string Occupation { get; set; }
        public string YearEmployed { get; set; }
        public string SSN { get; set; }
        public string TypeCust { get; set; }
        public string Sex { get; set; }
        public string Married { get; set; }
        public string BusSince { get; set; }
        public string TypeEntity { get; set; }
        public string Prod1Code { get; set; }
        public string CsrCode { get; set; }
        public string GLDivCode { get; set; }
        public string GLDeptCode { get; set; }
        public string DBA { get; set; }
        public string Active { get; set; }
        public string MarineAreaCode { get; set; }
        public string MarinePhone { get; set; }
        public string MarineExt { get; set; }
        public string BrokerCode { get; set; }
        public string NonPC { get; set; }
        public string LateCharge { get; set; }
        public string CollectLetter { get; set; }
        public string ReportOption { get; set; }
        public string AutoApplyPay { get; set; }
        public string StatePrintGroup { get; set; }
        public string AutoApplyCR { get; set; }
        public string NAICS { get; set; }
        public Nullable<System.Guid> LLId { get; set; }
        public string PrintCustStmt { get; set; }
        public System.DateTime ARClosedDate { get; set; }
        public string ARClosedStatus { get; set; }
        public string MktgFlag { get; set; }
        public string IsExclDelete { get; set; }
        public string MasterSubType { get; set; }
        public Nullable<System.Guid> MasterCustId { get; set; }
        public string PagerAreaCode { get; set; }
        public string PagerPhone { get; set; }
        public string PagerExt { get; set; }
        public string OtherAreaCode { get; set; }
        public string OtherPhone { get; set; }
        public string OtherExt { get; set; }
        public string EMail { get; set; }
        public string EMail2 { get; set; }
        public Nullable<System.Guid> ANotId { get; set; }
        public string FedIdNo { get; set; }
        public string DUNSNo { get; set; }
        public string IsBillNameSameAsCust { get; set; }
        public string BillName { get; set; }
        public string IsBillAddrSameAsCust { get; set; }
        public string BillAddr1 { get; set; }
        public string BillAddr2 { get; set; }
        public string BillCity { get; set; }
        public string BillState { get; set; }
        public string BillZip { get; set; }
        public string BillCounty { get; set; }
        public string MasterSubTrack { get; set; }
        public string IsPrintAgencyBill { get; set; }
        public string IsPrintDirectBill { get; set; }
        public string PremOption { get; set; }
        public string GroupingOption { get; set; }
        public string FirmNameCust { get; set; }
        public string IsBrokCust { get; set; }
        public string IsDeriveAttrFlagsCust { get; set; }
        public string PermAttrFlagsCust { get; set; }
        public string UserAttrFlagsCust { get; set; }
        public Nullable<double> LatitudeCust { get; set; }
        public Nullable<double> LongitudeCust { get; set; }
        public Nullable<System.DateTime> CustAddedDate { get; set; }
        public string GLBrnchCode { get; set; }
        public string GLGrpCode { get; set; }
        public string WebAddr { get; set; }
        public string TypeName { get; set; }
        public string FormalSalutation { get; set; }
        public string InformalSalutation { get; set; }
        public string IsSecured { get; set; }
        public string SortName { get; set; }
        public string BusOriginCode { get; set; }
        public string AcquisitionCode { get; set; }
        public string JoinCriteria { get; set; }
        public string ResFullPhone { get; set; }
        public string BusFullPhone { get; set; }
        public string FaxFullPhone { get; set; }
        public string MarineFullPhone { get; set; }
        public string PagerFullPhone { get; set; }
        public string OtherFullPhone { get; set; }
        public string DriversLicense { get; set; }
        public string TypeOfBusiness { get; set; }
        public string SIC { get; set; }
        public string GLCode { get; set; }
        public string MethodOfDistribution { get; set; }
        public string ChangedBy { get; set; }
        public System.DateTime ChangedDate { get; set; }
        public System.DateTime EnteredDate { get; set; }
    }
}
