//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvansApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EvansDBEntities : DbContext
    {
        public EvansDBEntities()
            : base("name=EvansDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AMS360_Customer> AMS360_Customer { get; set; }
        public virtual DbSet<HZ_Cards> HZ_Cards { get; set; }
        public virtual DbSet<HZ_CD_IRA> HZ_CD_IRA { get; set; }
        public virtual DbSet<HZ_Customer> HZ_Customer { get; set; }
        public virtual DbSet<HZ_DD_SV> HZ_DD_SV { get; set; }
        public virtual DbSet<HZ_LN> HZ_LN { get; set; }
        public virtual DbSet<HZ_ML> HZ_ML { get; set; }
        public virtual DbSet<HZ_SafeDepBox> HZ_SafeDepBox { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<WM_AdvisorsAssistant> WM_AdvisorsAssistant { get; set; }
        public virtual DbSet<WM_LPL> WM_LPL { get; set; }
        public virtual DbSet<WM_PersonalLines> WM_PersonalLines { get; set; }
        public virtual DbSet<MD_LinkedCustomers> MD_LinkedCustomers { get; set; }
    }
}
