//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvansApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HZ_Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HZ_Customer()
        {
            this.HZ_Cards = new HashSet<HZ_Cards>();
            this.HZ_CD_IRA = new HashSet<HZ_CD_IRA>();
            this.HZ_DD_SV = new HashSet<HZ_DD_SV>();
            this.HZ_LN = new HashSet<HZ_LN>();
            this.HZ_ML = new HashSet<HZ_ML>();
            this.HZ_SafeDepBox = new HashSet<HZ_SafeDepBox>();
        }
    
        public System.DateTime BossProccessDate { get; set; }
        public int CustomerKey { get; set; }
        public string CustomerType { get; set; }
        public string CustomerName { get; set; }
        public string ServiceMember { get; set; }
        public string DriverID { get; set; }
        public Nullable<System.DateTime> DriverIDIssueDate { get; set; }
        public Nullable<System.DateTime> DriverIDExpirationDate { get; set; }
        public string DriverIDIssueState { get; set; }
        public string PassPortID { get; set; }
        public Nullable<System.DateTime> PassPortIssueDate { get; set; }
        public Nullable<System.DateTime> PassPortExpirationDate { get; set; }
        public string PassPortIssueCountry { get; set; }
        public string TaxpayerIDMasked { get; set; }
        public string TaxpayerIDFull { get; set; }
        public string ForeignTaxID { get; set; }
        public string Address1StreetNumber { get; set; }
        public string Address1StreetName { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public Nullable<int> Zipcode { get; set; }
        public Nullable<int> Zipcode_plus_4 { get; set; }
        public string ForeignCountryCode { get; set; }
        public string ForeignPostalCode { get; set; }
        public string CommentLine { get; set; }
        public string CreditBureauReportCode { get; set; }
        public string Prefix { get; set; }
        public string ProfessionalDesignation { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Suffix { get; set; }
        public string NonPersonalNameLine1 { get; set; }
        public string NonPersonalNameLine2 { get; set; }
        public string RegOCode { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> InactiveDate { get; set; }
        public Nullable<int> BranchCode { get; set; }
        public string Branch { get; set; }
        public string CommSpecUseNbr { get; set; }
        public string IVRAccessFlag { get; set; }
        public string InternetAccessFlag { get; set; }
        public string InternetAddress { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public Nullable<System.DateTime> LastCustomerContactDate { get; set; }
        public Nullable<System.DateTime> DateCustomerAdded { get; set; }
        public Nullable<System.DateTime> LostCustomerDate { get; set; }
        public string HomePhone { get; set; }
        public string CellPhone { get; set; }
        public string BusinessPhone { get; set; }
        public string Privacy_Sharing_Option { get; set; }
        public System.DateTime LoadedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HZ_Cards> HZ_Cards { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HZ_CD_IRA> HZ_CD_IRA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HZ_DD_SV> HZ_DD_SV { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HZ_LN> HZ_LN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HZ_ML> HZ_ML { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HZ_SafeDepBox> HZ_SafeDepBox { get; set; }
    }
}
