//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvansApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HZ_CD_IRA
    {
        public Nullable<System.DateTime> BossProcessDate { get; set; }
        public int PrimaryCustomerKey { get; set; }
        public string AccountNo { get; set; }
        public string CustomerName { get; set; }
        public string Application { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public string AccuredInterest { get; set; }
        public Nullable<int> Branch { get; set; }
        public string ClosedDate { get; set; }
        public Nullable<int> CompoundFrequency { get; set; }
        public Nullable<int> CompoundFrequencyIncrement { get; set; }
        public Nullable<int> BranchNo { get; set; }
        public string CurrencyCode { get; set; }
        public string Product { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public Nullable<int> EndXrefRate { get; set; }
        public Nullable<int> ExtXrefPrice { get; set; }
        public string GLAcount { get; set; }
        public string GlType { get; set; }
        public string InterestCreditFlag { get; set; }
        public Nullable<int> InterestPaymentFrequency { get; set; }
        public Nullable<int> InterestPaymentFrequencyIncrement { get; set; }
        public string Rate { get; set; }
        public Nullable<int> BaseXrefRate { get; set; }
        public Nullable<System.DateTime> MaturityDate { get; set; }
        public Nullable<int> NextCompound { get; set; }
        public Nullable<System.DateTime> NextPayment { get; set; }
        public Nullable<decimal> OriginalBalance { get; set; }
        public Nullable<int> OriginalTerm { get; set; }
        public Nullable<System.DateTime> OpenDate { get; set; }
        public string AccuralBasis { get; set; }
        public string OrigTermIncrement { get; set; }
        public string Determine_A_M_D { get; set; }
        public Nullable<System.DateTime> NextInterestPaymentDate { get; set; }
        public Nullable<int> PaymentFrequency { get; set; }
        public Nullable<int> PaymentFrequencyIncrement { get; set; }
        public Nullable<int> PaymentType { get; set; }
        public Nullable<int> PercentOwned { get; set; }
        public string IPSCode { get; set; }
        public Nullable<System.DateTime> RepriceDate { get; set; }
        public Nullable<decimal> RolloverBalance { get; set; }
        public Nullable<System.DateTime> RolloverDate { get; set; }
        public Nullable<int> RateChangeFrequency { get; set; }
        public string RateChangeType { get; set; }
        public string RenewalFlag { get; set; }
        public Nullable<System.DateTime> LastRenewalDate { get; set; }
        public Nullable<decimal> AverageBalance { get; set; }
        public Nullable<int> RepriceIndex { get; set; }
        public Nullable<int> RePriceSpread { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> TaxExemptionFlag { get; set; }
        public Nullable<int> TaxExemptL { get; set; }
        public Nullable<int> TaxExemptS { get; set; }
        public Nullable<int> Transfer_I_E { get; set; }
        public Nullable<int> TransferRate { get; set; }
        public Nullable<int> WAC { get; set; }
        public Nullable<int> WAM { get; set; }
        public System.DateTime LoadedDate { get; set; }
        public Nullable<decimal> PerDiem { get; set; }
    
        public virtual HZ_Customer HZ_Customer { get; set; }
    }
}
