//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvansApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HZ_LN
    {
        public Nullable<System.DateTime> BossProcessDate { get; set; }
        public int PrimaryCustomerKey { get; set; }
        public string AccountNumber { get; set; }
        public string CustomerName { get; set; }
        public string AccountStatus { get; set; }
        public Nullable<decimal> CurrentPrincipalBalance { get; set; }
        public string ProductCode { get; set; }
        public string Product { get; set; }
        public string OfficerCode { get; set; }
        public string Officer1Name { get; set; }
        public string Branch { get; set; }
        public Nullable<int> BranchNumber { get; set; }
        public Nullable<decimal> CreditRiskCode { get; set; }
        public Nullable<int> DaysPastDue { get; set; }
        public string CollateralType { get; set; }
        public string CollateralTypeCode { get; set; }
        public Nullable<System.DateTime> CurrentMaturityDate { get; set; }
        public Nullable<System.DateTime> OriginalMaturityDate { get; set; }
        public string GLType { get; set; }
        public string GLTypeCode { get; set; }
        public string BUP { get; set; }
        public string Application { get; set; }
        public string ReservedforFutureUse1 { get; set; }
        public string BillOption { get; set; }
        public Nullable<decimal> AvailableBalance { get; set; }
        public string ImpairedAssetStatus { get; set; }
        public string InterestTypeIndicator { get; set; }
        public string InterestRate { get; set; }
        public string EscrowInterestPerDiem { get; set; }
        public Nullable<decimal> OrigConstantAmount { get; set; }
        public Nullable<decimal> UnearnedAmount { get; set; }
        public string SystemType { get; set; }
        public string PaySplitOption { get; set; }
        public string EscrowFlag { get; set; }
        public string InsuranceFlag { get; set; }
        public string ReservedforFutureUse2 { get; set; }
        public string PartialPaymentFlag { get; set; }
        public string LateChargeWaiveCode { get; set; }
        public string DeferredFeesFASB { get; set; }
        public Nullable<decimal> ParticipationsSold { get; set; }
        public Nullable<decimal> BankOwnedPrincipalBalance { get; set; }
        public Nullable<System.DateTime> ParticipationAgreementDatePS { get; set; }
        public string ImpairedAssetFlag { get; set; }
        public Nullable<decimal> BankOwnedPrincipalAssets { get; set; }
        public Nullable<decimal> CurBilledPaymentAmount { get; set; }
        public Nullable<decimal> CurrentEscrowBalance { get; set; }
        public Nullable<decimal> CurrentLoanAmount { get; set; }
        public Nullable<decimal> CurtailmentBalance { get; set; }
        public Nullable<decimal> PayoffAmount { get; set; }
        public Nullable<decimal> TotalDue { get; set; }
        public Nullable<decimal> UnappliedBalance { get; set; }
        public Nullable<decimal> EscrowBilled { get; set; }
        public string CallReportCode { get; set; }
        public Nullable<decimal> InsuranceBilled { get; set; }
        public Nullable<decimal> PrincipalBilled { get; set; }
        public Nullable<decimal> FeesBilled { get; set; }
        public Nullable<decimal> LateChargesDue { get; set; }
        public Nullable<decimal> PastDuePrincipal { get; set; }
        public Nullable<decimal> PastDueInterest { get; set; }
        public Nullable<decimal> PastDueInsurance { get; set; }
        public Nullable<decimal> PastDueFees { get; set; }
        public Nullable<decimal> PastDueEscrow { get; set; }
        public Nullable<decimal> TotalPastDue { get; set; }
        public Nullable<decimal> Pre_PaidEscrow { get; set; }
        public Nullable<decimal> Pre_PaidInterest { get; set; }
        public Nullable<decimal> Pre_PaidPrincipal { get; set; }
        public Nullable<decimal> NextEscrowPayment { get; set; }
        public Nullable<decimal> InterestBilled { get; set; }
        public Nullable<decimal> UnearnedInterest { get; set; }
        public Nullable<decimal> UnearnedNetEarnings { get; set; }
        public Nullable<decimal> UnearnedNetCost { get; set; }
        public Nullable<decimal> OriginalAmountChargedOff { get; set; }
        public Nullable<decimal> OriginalAmounttoNon_Accrual { get; set; }
        public Nullable<decimal> BookBalance { get; set; }
        public Nullable<int> ParticipationCount { get; set; }
        public string CurrentPercentSoldPS { get; set; }
        public Nullable<decimal> CurrentPrincipalBalancePS { get; set; }
        public Nullable<System.DateTime> NextDueDate { get; set; }
        public Nullable<int> C30DaysPastDue { get; set; }
        public Nullable<int> C60DaysPastDue { get; set; }
        public Nullable<int> C90DaysPastDue { get; set; }
        public Nullable<int> C120DaysPastDue { get; set; }
        public Nullable<System.DateTime> LastPaymentDate { get; set; }
        public string AccountStatusCode { get; set; }
        public Nullable<System.DateTime> OriginalNoteDate { get; set; }
        public Nullable<decimal> MarketValue { get; set; }
        public string TroubledDebtRestructured { get; set; }
        public Nullable<System.DateTime> Non_AccrualDate { get; set; }
        public Nullable<decimal> InterestEarnedSinceImpairedDate { get; set; }
        public string InterestEarnedtoImpairedDate { get; set; }
        public string FractionalAccruedInterest { get; set; }
        public Nullable<decimal> TotalAccruedInterest { get; set; }
        public Nullable<decimal> InterestPaidYTD { get; set; }
        public Nullable<decimal> CycleAccrual { get; set; }
        public Nullable<int> NAICSCode { get; set; }
        public string NAICSDescription { get; set; }
        public string NAICSSector { get; set; }
        public string NAICSSubSectorLevel1 { get; set; }
        public string NAICSSubSectorLevel2 { get; set; }
        public string NAICSSubSectorLevel3 { get; set; }
        public Nullable<System.DateTime> RateResetDate { get; set; }
        public Nullable<System.DateTime> BoardingDate { get; set; }
        public Nullable<System.DateTime> BoardingDate_DeferredEarnings { get; set; }
        public Nullable<decimal> AverageBookBalanceMTD { get; set; }
        public Nullable<decimal> AverageBookBalanceQTD { get; set; }
        public Nullable<decimal> AverageBookBalanceYTD { get; set; }
        public string PurchasedCode { get; set; }
        public string PurchasedCodeDescription { get; set; }
        public string NameAddressLine2 { get; set; }
        public string NameAddressLine3 { get; set; }
        public string NameAddressLine4 { get; set; }
        public string NameAddressLine5 { get; set; }
        public string NameAddressLine6 { get; set; }
        public string PurposeCode { get; set; }
        public string Purpose { get; set; }
        public Nullable<int> LienPosition { get; set; }
        public string TDRDate { get; set; }
        public string TDRDetermination { get; set; }
        public string TDRConcessionCode { get; set; }
        public string MasterTrancheFlag { get; set; }
        public string PurchasedParticipations { get; set; }
        public System.DateTime LoadedDate { get; set; }
        public Nullable<decimal> InterestPerDiem { get; set; }
    
        public virtual HZ_Customer HZ_Customer { get; set; }
    }
}
