//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvansApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HZ_ML
    {
        public Nullable<System.DateTime> BossProcessDate { get; set; }
        public int PrimaryCustomerKey { get; set; }
        public string LoanNumber { get; set; }
        public string Name { get; set; }
        public string Status { get; set; }
        public Nullable<decimal> CurrentPrincipalBalance { get; set; }
        public string Product { get; set; }
        public string ProductCode { get; set; }
        public string OfficerCode { get; set; }
        public string OfficerName { get; set; }
        public string Branch { get; set; }
        public Nullable<int> BranchNumber { get; set; }
        public string CreditRisk { get; set; }
        public Nullable<int> DaysPastDue { get; set; }
        public string CollateralType { get; set; }
        public string CollateralTypeCode { get; set; }
        public Nullable<System.DateTime> CurrentMaturityDate { get; set; }
        public Nullable<System.DateTime> OriginalMaturityDate { get; set; }
        public string GLType { get; set; }
        public string GLTypeCode { get; set; }
        public string BupCode { get; set; }
        public string LoanType { get; set; }
        public string ARMType { get; set; }
        public string BillMethod { get; set; }
        public string ChargeOffStatus { get; set; }
        public string DelinquentFlag { get; set; }
        public string InterestCalculationMethod { get; set; }
        public string CurrentInterestRate { get; set; }
        public string EscrowInterestRate { get; set; }
        public Nullable<decimal> UnamortizedFAS91Fees { get; set; }
        public Nullable<decimal> UnamortizedFAS91Costs { get; set; }
        public Nullable<decimal> FeeUnearnedRemaining { get; set; }
        public Nullable<decimal> NonAccrualInterestPaid { get; set; }
        public Nullable<decimal> MinPaymentAmount { get; set; }
        public Nullable<decimal> PnIPaymentAmount { get; set; }
        public Nullable<decimal> TotalPaymentAmount { get; set; }
        public string AutoTransferFlag { get; set; }
        public string ConstructionType { get; set; }
        public string EscrowInterestFlag { get; set; }
        public Nullable<int> GracePeriod { get; set; }
        public string InterestOnlyPaymentFlag { get; set; }
        public string PartialPaymentFlag { get; set; }
        public string PMICoverageFlag { get; set; }
        public Nullable<decimal> ChargeOffAmount { get; set; }
        public Nullable<decimal> FeesDueAmount { get; set; }
        public Nullable<decimal> LateChargeDue { get; set; }
        public Nullable<decimal> NonAccrualPrincipalBalance { get; set; }
        public Nullable<decimal> PrincipalPastDue { get; set; }
        public Nullable<decimal> EscrowPastDue { get; set; }
        public string AccruedEscrowInterest { get; set; }
        public Nullable<decimal> EscrowBalance { get; set; }
        public Nullable<decimal> EscrowPaymentAmount { get; set; }
        public string FullAmortPayment { get; set; }
        public string AccountNumberAutoTransfers { get; set; }
        public Nullable<System.DateTime> CurrentPaymentDueDate { get; set; }
        public Nullable<decimal> OriginalPrincipalBalance { get; set; }
        public Nullable<decimal> BookBalance { get; set; }
        public Nullable<int> ParticipationCount { get; set; }
        public string PercentSold { get; set; }
        public Nullable<System.DateTime> SaleDate { get; set; }
        public Nullable<decimal> CurrentPrincipalDueInvestor { get; set; }
        public string PropertyTypeCode { get; set; }
        public string PropertyUsage { get; set; }
        public Nullable<int> PastDue90_119 { get; set; }
        public Nullable<int> PastDue60_89 { get; set; }
        public Nullable<int> PastDue30_59 { get; set; }
        public Nullable<int> PastDue120 { get; set; }
        public Nullable<System.DateTime> OriginalDate { get; set; }
        public Nullable<System.DateTime> NextInterestReviewDate { get; set; }
        public Nullable<decimal> NetPayoffAmount { get; set; }
        public string TotalCTMarketValue { get; set; }
        public string RiskCode { get; set; }
        public Nullable<decimal> OriginalFee1 { get; set; }
        public string TroubledDebtRestructured { get; set; }
        public Nullable<int> ModifyLoanCode { get; set; }
        public Nullable<System.DateTime> LastModifyDate { get; set; }
        public Nullable<decimal> InterestEarnedMTD { get; set; }
        public Nullable<decimal> InterestEarnedQTD { get; set; }
        public Nullable<decimal> InterestEarnedYTD { get; set; }
        public Nullable<decimal> RecoveryMTD { get; set; }
        public Nullable<decimal> RecoveryQTD { get; set; }
        public Nullable<decimal> RecoveryYTD { get; set; }
        public Nullable<decimal> InterestAccrued { get; set; }
        public Nullable<decimal> AccruedInterestCurrentPeriod { get; set; }
        public Nullable<decimal> CapitalInterestBalance { get; set; }
        public Nullable<decimal> FracAccruedInterest { get; set; }
        public Nullable<decimal> InterestPaidYTD { get; set; }
        public Nullable<decimal> InterestPastDue { get; set; }
        public Nullable<decimal> InterestPerDiem { get; set; }
        public Nullable<decimal> NA_InterestatStop { get; set; }
        public Nullable<decimal> NA_InterestfromStop { get; set; }
        public Nullable<decimal> PrevYearInterestPaid { get; set; }
        public Nullable<decimal> PriorInterestPaidinNA { get; set; }
        public Nullable<decimal> TotalAccruedInterest { get; set; }
        public Nullable<int> OriginalBranch { get; set; }
        public Nullable<int> NAICSCode { get; set; }
        public string CallReportCode { get; set; }
        public Nullable<decimal> PrepaidUnappliedBalance { get; set; }
        public Nullable<System.DateTime> RateResetDate { get; set; }
        public Nullable<decimal> ParticipationsSold { get; set; }
        public string CTAddress1StreetNumber { get; set; }
        public string CTAddress1StreetName { get; set; }
        public string CTAddress2StreetNumber { get; set; }
        public string CTAddress2StreetName { get; set; }
        public string CTAddress3StreetNumber { get; set; }
        public string CTAddress3StreetName { get; set; }
        public string CTCity { get; set; }
        public string CTState { get; set; }
        public string CTZipCode { get; set; }
        public string CTZipCode4 { get; set; }
        public Nullable<decimal> AverageBookBalanceMTD { get; set; }
        public Nullable<decimal> AverageBookBalanceQTD { get; set; }
        public Nullable<decimal> AverageBookBalanceYTD { get; set; }
        public string PurposeCode { get; set; }
        public string Purpose { get; set; }
        public Nullable<int> LienPosition { get; set; }
        public Nullable<System.DateTime> BoardingDate { get; set; }
        public Nullable<decimal> BankOwnedPrincipalAssets { get; set; }
        public string TDRDate { get; set; }
        public string TDRDetermination { get; set; }
        public Nullable<int> TDRConcessionCode { get; set; }
        public string MLOriginalLTV { get; set; }
        public System.DateTime LoadedDate { get; set; }
    
        public virtual HZ_Customer HZ_Customer { get; set; }
    }
}
