//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvansApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HZ_SafeDepBox
    {
        public Nullable<System.DateTime> BossProcessDate { get; set; }
        public Nullable<int> PrimaryCustomerKey { get; set; }
        public string TINClearValue { get; set; }
        public string AccountNumber { get; set; }
        public Nullable<System.DateTime> DateOpened { get; set; }
        public string BranchNo { get; set; }
        public string Branch { get; set; }
        public string Status { get; set; }
        public Nullable<decimal> AmountDue { get; set; }
        public Nullable<System.DateTime> DateNextPaymentDue { get; set; }
        public Nullable<decimal> BoxPrice { get; set; }
        public Nullable<decimal> SalesTaxDue { get; set; }
        public Nullable<int> PastDueTimes { get; set; }
        public Nullable<decimal> TotalBoxAmountPastDue { get; set; }
        public Nullable<decimal> TotalTaxAmountPastDue { get; set; }
        public System.DateTime LoadedDate { get; set; }
    
        public virtual HZ_Customer HZ_Customer { get; set; }
    }
}
