//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvansApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MD_LinkedCustomers
    {
        public string Results { get; set; }
        public int GroupID { get; set; }
        public Nullable<int> NewCount { get; set; }
        public string MD_FirstName { get; set; }
        public string MD_LastName { get; set; }
        public string MD_Address { get; set; }
        public string MD_Address2 { get; set; }
        public string MD_City { get; set; }
        public string MD_State { get; set; }
        public string MD_Zip { get; set; }
        public string MD_Results { get; set; }
        public string FullName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string TaxID { get; set; }
        public string Source { get; set; }
        public string MD_DriverID { get; set; }
        public Nullable<int> AMS360_CustNum { get; set; }
        public Nullable<int> HZ_CustomerKey { get; set; }
        public Nullable<int> LPL_ID { get; set; }
        public Nullable<int> PER_ID { get; set; }
        public Nullable<int> AA_ID { get; set; }
        public string MD_Email { get; set; }
    }
}
