//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvansApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WM_AdvisorsAssistant
    {
        public int ID { get; set; }
        public string FullName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<long> TaxID { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZipCode { get; set; }
        public string CoveragePlan { get; set; }
        public string CoverageTypeDesc { get; set; }
        public Nullable<decimal> CoverageBenefit { get; set; }
        public string CoverageStatus { get; set; }
        public Nullable<System.DateTime> CoverageEffectiveDate { get; set; }
        public Nullable<decimal> PermiumCoverageAnnualTotal { get; set; }
        public Nullable<decimal> CommissionCoverage1stYearTotal { get; set; }
        public Nullable<System.DateTime> LoadDate { get; set; }
    }
}
