//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvansApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WM_PersonalLines
    {
        public int ID { get; set; }
        public string CustomerName { get; set; }
        public Nullable<int> CustomerNumber { get; set; }
        public string CustomerType { get; set; }
        public string ActiveCustomer { get; set; }
        public string PolicyNumber { get; set; }
        public string Department { get; set; }
        public string Division { get; set; }
        public string CustomerExecutive { get; set; }
        public string CustomerEmail { get; set; }
        public string CustomerRepresentative { get; set; }
        public string BrokerName { get; set; }
        public string CustomerPhoneNumberResidential { get; set; }
        public string CustomerPhoneNumberBusiness { get; set; }
        public Nullable<System.DateTime> PolicyEffectiveDate { get; set; }
        public Nullable<System.DateTime> PolicyExpirationDate { get; set; }
        public string PolicyStatus { get; set; }
        public string TypeOfBusiness { get; set; }
        public string PolicyExecutive { get; set; }
        public string PolicyRepresentative { get; set; }
        public string PolicyBroker { get; set; }
        public string ParentCompany { get; set; }
        public string WritingCompany { get; set; }
        public string PolicyDescription { get; set; }
        public string PolicyDepartment { get; set; }
        public string IsContinuous { get; set; }
        public string BusinessNewToAgency { get; set; }
        public Nullable<System.DateTime> CustomerAddDate { get; set; }
        public string Underwriter { get; set; }
        public string AdditionalExecutives { get; set; }
        public string AdditionalRepresentatives { get; set; }
        public string AdditionalSalesCenterRepresentatives { get; set; }
        public string PolicyDivison { get; set; }
        public string BillMethod { get; set; }
        public string PolicyNotation { get; set; }
        public string DBA { get; set; }
        public string CustomerAddress1 { get; set; }
        public string CustomerCity { get; set; }
        public string CustomerCounty { get; set; }
        public string CustomerState { get; set; }
        public string CustomerZipCode { get; set; }
        public Nullable<int> InBusinessSince { get; set; }
        public string MatrialStatus { get; set; }
        public string Occupation { get; set; }
        public string BrokerAddress1 { get; set; }
        public string BrokerCity { get; set; }
        public string BrokerState { get; set; }
        public string BrokerZip { get; set; }
        public string BrokerBusinessPhone { get; set; }
        public string BrokerEmail { get; set; }
        public string Notation { get; set; }
        public string PolicyContactName { get; set; }
        public string PolicyContactResponsibility { get; set; }
        public string PolicyContactPhone { get; set; }
        public string PolicyContactPhoneBusiness { get; set; }
        public string PolicyContactEmail { get; set; }
        public string LineOfBusiness { get; set; }
        public string PolicyID { get; set; }
        public string CustomerEmail2 { get; set; }
        public string CustomerAddress2 { get; set; }
        public Nullable<System.DateTime> LoadDate { get; set; }
    }
}
